[package]
name = "file_explorer_term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8.0"
serde = { version="1.0.164", features=["derive"] }
serde_json = "1.0.99"
sysinfo = "0.29.2"

