[package]
name = "iced_wasmer_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.10.0"

[patch.crates-io]
libc = { git = "https://github.com/wasix-org/libc", branch = "master" }
